[global]
[template]

[[template.pass]]
role = 'parent'
path = ''
cmd = 'make insmod ID=0'
order = 0

[[template.pass]]
role = 'child'
path = ''
cmd = 'make insmod ID=${@incr}'
order = 0

[[template.pass]]
role = 'child'
path = 'exp'
cmd = './connector -gid=${parent_gid} -mac_id=0 -nic_id=0'
order = 1

[[template.pass]]
role = 'parent'
path = 'exp/fork-functions'
cmd = 'cd ${micro_func_name} && python function.py -exclude_execution=0 -pin=1 -profile=0 -handler_id=73'
order = 2


[[template.pass]]
role = 'child'
path = ''
cmd = 'make bench_lean_mitosis mac_id=0 LEAN_BENCH_EXE_PATH=${exe_name} LEAN_APP_NAME=simple_child BENCH_SEC=${run_sec}'
#path = 'exp'
#cmd = './simple_child'
order = 3
loop = 24

[template.placeholder]
micro_func_name = [
    "micro",
    "json",
    "chameleon",
    "compression",
    "helloworld",
    "image",
    "pagerank",
    "pyaes",
    "recognition"
]
exe_name = "exp/bench_lean_container"
run_sec = 30
