pwd = "20170150lfm-IPADS"
user = "lfm"
path = "projects/mos"
[[pass]]
host = 'val06'
path = '/home/lfm/projects/mos/exp'
cmd = 'make -j && cp lean_child fork-functions/child/.'


[[pass]]
host = 'val06'
path = '/home/lfm/projects/mos/mitosis-user-libs/mitosis-lean-container'
cmd = ' make export mount_dev COMMAND_ABS_PATH=/app/lean_child PATH_TO_APP=app/simple_child'

