[[pass]]
host = 'val07'
path = '/home/lfm/projects/mos'
cmd = 'make insmod'
[[pass]]
host = 'val08'
path = '/home/lfm/projects/mos'
cmd = 'make insmod'

[[pass]]
host = 'val08'
path = '/home/lfm/projects/mos/exp'
cmd = './connector -gid=fe80:0000:0000:0000:248a:0703:009c:7ca8 -mac_id=1 -nic_id=0'


[[pass]]
host = 'val07'
path = '/home/lfm/projects/mos/exp/fork-functions/micro'
cmd = 'python function.py -touch_ratio=100 -working_set=67108864 -exclude_execution=0 -handler_id=73 -pin=1 -profile=0 -app_name="micro-touch-ratio" '


[[pass]]
host = 'val08'
path = '/home/lfm/projects/mos/exp/scripts'
cmd = 'sh run_lean_container.sh'
