[global]
[template]

[[template.pass]]
role = 'builder'
path = 'stress-test/rpc'
cmd = 'source $HOME/.profile; cp Kbuild-checksum-payload Kbuild; ./build_tests.py rpc_server rpc_client'

[template.placeholder]
name = ["build"]
