[package]
name = "rpc_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = {features=["raw"], path="../../../deps/hashbrown"}
