[global]
[template]

[[template.pass]]
role = 'parent'
path = ''
cmd = 'make insmod'
order = 0

[[template.pass]]
role = 'child'
path = ''
cmd = 'make insmod'
order = 0

[[template.pass]]
role = 'child'
path = 'exp'
cmd = './connector -gid=${parent_gid} -mac_id=${@incr} -nic_id=0'
order = 1
[[template.pass]]
role = 'parent'
path = 'exp/fork-functions'
cmd = 'cd ${micro_func_name} && python function.py -exclude_execution=0 -pin=1 -profile=0 -handler_id=73'
order = 1

[[template.pass]]
role = 'child'
path = ''
cmd = 'make bench_lean_mitosis mac_id=${@incr} LEAN_APP_NAME=simple_child BENCH_SEC=${run_sec}'
order = 2
loop = 2

[template.placeholder]
micro_func_name = [
    "micro",
    "json",
    "chameleon",
    "compression",
    "helloworld",
    "image",
    "pagerank",
    "pyaes",
    "recognition"
]
run_sec = 8