[global]
[template]

[[template.pass]]
role = 'builder'
path = ''
cmd = 'source $HOME/.cargo/env; cp mitosis-kms/${Kbuild} mitosis-kms/Kbuild && make clean ; make km ; make insmod'

[template.placeholder]
name = ["build"]
Kbuild = "Kbuild-mitosis-cache"


