[global]
[template]

[[template.pass]]
role = 'builder'
path = 'exp'
cmd = 'sudo umount ${tmp_dir} ;sudo mkdir -p ${tmp_dir} ; echo ${micro_func_name}'

[template.placeholder]
tmp_dir="/tmp-mitosis"
micro_func_name = ["json", "chameleon", "compression", "helloworld", "image", "pagerank", "pyaes", "recognition"]
