[global]
[template]

[[template.pass]]
role = 'child'
path = 'exp'
cmd = 'make -j && cp lean_child fork-functions/child/.'

[[template.pass]]
role = 'child'
path = ''
cmd = 'make export mount_dev LEAN_APP_NAME=simple_child'

[template.placeholder]
name = ["build"]


