[[pass]]
host = 'val07'
path = '/home/lfm/projects/mos/exp'
cmd = 'make insmod'
[[pass]]
host = 'val08'
path = '/home/lfm/projects/mos/exp'
cmd = 'make insmod'

[[pass]]
host = 'val07'
path = '/home/lfm/projects/mos/exp/fork-micro'
cmd = './connector -gid=fe80:0000:0000:0000:248a:0703:009c:7c94 -mac_id=1 -nic_id=0'


[[pass]]
host = 'val08'
path = '/home/lfm/projects/mos/exp/fork-micro'
cmd = 'python ./bench_exe_time_parent.py -working_set=268435456 -run_sec=5'

[[pass]]
host = 'val07'
path = '/home/lfm/projects/mos/exp/fork-micro'
cmd = './simple_child -mac_id=1'
