[[pass]]
host = 'val08'
path = '/home/lfm/projects/mos/exp'
cmd = 'source $HOME/.cargo/env; make rmmod'

[[pass]]
host = 'val07'
path = '/home/lfm/projects/mos/exp'
cmd = 'source $HOME/.cargo/env; make rmmod'


[[pass]]
host = 'val08'
path = '/home/lfm/projects/mos/mitosis-user-libs/mitosis-lean-container'
cmd = 'make clean_fs COMMAND_ABS_PATH=/app/lean_child PATH_TO_APP=../../exp/fork-functions/child'

