[global]
[template]

[[template.pass]]
role = 'parent'
path = ''
cmd = 'echo 3 | sudo tee /proc/sys/vm/drop_caches; make insmod'


[[template.pass]]
role = 'parent'
path='exp' ## c-version
cmd='sleep 1 && ./bench_workingset --working_set=${working_set} --whether_prepare=1 -exclude_execution=0'

[[template.pass]]
role = 'parent'
path = 'exp'
cmd = './simple_child -mac_id=0 -wait_finish_sec=5; for i in seq 1 3 ;do ./simple_child -mac_id=0 ;done; for i in seq 1 3 ;do ./simple_child -mac_id=0 ;done'

[template.placeholder]
working_set = [
    1048576,
    4194304,
    8388608,
    16777216,
    33554432,
    67108864,
    134217728,
    268435456,
    536870912,
    1073741824,
]
micro_func_name = "micro"

