[global]
[template]

[[template.pass]]
role = 'parent'
path = ''
cmd = 'echo 3 | sudo tee /proc/sys/vm/drop_caches; make insmod'
order = 0


[[template.pass]]
role = 'parent'
path='exp' ## c-version
cmd = 'for i in seq 1 3; do for i in seq 1 3 ;do ./bench_workingset --working_set=${working_set} -exclude_execution=0 --whether_prepare=1;cd ../;make insmod;cd exp ;done; done'
order = 1

[template.placeholder]
working_set = [
    1048576,
    4194304,
    8388608,
    16777216,
    33554432,
    67108864,
    134217728,
    268435456,
    536870912,
    1073741824,
]
micro_func_name = "micro"

