[[pass]]
host = 'val07'
path = '/home/lfm/projects/mos'
cmd = 'make insmod'
[[pass]]
host = 'val08'
path = '/home/lfm/projects/mos'
cmd = 'make insmod'

[[pass]]
host = 'val08'
path = '/home/lfm/projects/mos/exp'
cmd = './connector -gid=fe80:0000:0000:0000:248a:0703:009c:7ca8 -mac_id=1 -nic_id=0'


[[pass]]
host = 'val07'
path = '/home/lfm/projects/mos/exp/fork-functions/micro'
cmd = 'python function.py -ret_imm=1 -working_set=134217728 -handler_id=73'


[[pass]]
host = 'val08'
path = '/home/lfm/projects/mos/exp/scripts'
cmd = 'sh run_lean_container.sh'
