[global]
[template]

[[template.pass]]
role = 'child'
path = ''
cmd = 'make bench_lean_mitosis mac_id=0 LEAN_APP_NAME=simple_child BENCH_SEC=${run_sec} LEAN_BENCH_EXE_PATH=${exe_name} empty_process=1'
order = 0
loop = 16

[template.placeholder]
exe_name = ["exp/bench_process_fork", "exp/bench_lean_container"]
run_sec = 15
