[global]
[template]

[[template.pass]]
role = 'parent'
path = 'exp/'
cmd = "./bench_workingset_exe -run_sec=${run_sec} -working_set=${working_set}"
order=0
loop=16

[template.placeholder]
working_set = [
    1048576,
    4194304,
    8388608,
    16777216,
    33554432,
    67108864,
    134217728,
    268435456,
    536870912,
    1073741824,
]
run_sec=20