[global]
[template]

[[template.pass]]
role = 'parent'
path = 'exp/fork-functions'
cmd = 'cd ${micro_func_name} && python function.py -profile=0 -run_once=1'
order=0
loop=2

[template.placeholder]
micro_func_name = ["micro", "json", "chameleon", "compression", "helloworld", "image", "pagerank", "pyaes", "recognition"]
