[global]
[template]

[[template.pass]]
role = 'parent'
path = ''
cmd = 'make insmod ID=0'
order = 0

[[template.pass]]
role = 'child'
path = ''
cmd = 'make insmod ID=${@incr}'
order = 0

[[template.pass]]
role = 'child'
path = 'exp'
cmd = './connector -gid=${parent_gid} -mac_id=0 -nic_id=0'
order = 1

[[template.pass]]
role = 'parent'
path = 'exp' ## c-version
cmd = "./bench_workingset --working_set=${working_set} -random=0 -profile=0 -whether_prepare=1 -exclude_execution=0  -touch_ratio=${touch_ratio}"
order = 2


[[template.pass]]
role = 'child'
path = ''
cmd = 'make bench_lean_mitosis mac_id=0 LEAN_BENCH_EXE_PATH=${exe_name} LEAN_APP_NAME=simple_child BENCH_SEC=${run_sec}'
order = 3
loop = 16

[template.placeholder]
working_set = 67108864
touch_ratio = [100]
#touch_ratio = [0, 20, 40, 50, 55, 60, 65, 70, 80, 85, 90, 95, 100]
exe_name = "exp/bench_lean_container"
run_sec = 30