[global]
[template]

[[template.pass]]
role = 'parent'
path = ''
cmd = 'echo helloworld'


[[template.pass]]
role = 'parent'
path = 'exp/fork-functions'
cmd = 'echo ${micro_func_name}'


[template.placeholder]
micro_func_name = ["micro", "json", "chameleon", "compression", "helloworld", "image", "pagerank", "pyaes", "recognition"]


