[global]
[template]

[[template.pass]]
role = 'parent'
path = ''
cmd = 'make insmod ID=0'
order = 0

[[template.pass]]
role = 'child'
path = ''
cmd = 'make insmod ID=${@incr}'
order = 0

[[template.pass]]
role = 'parent'
path = 'exp/fork-functions'
cmd = 'cd ${micro_func_name} && python function.py -exclude_execution=0 -handler_id=73 -pin=1 -hang=1 -profile=1 -app_name="${micro_func_name}" '
order = 1

[[template.pass]]
role = 'child'
path = 'exp'
cmd = './connector -gid=${parent_gid} -mac_id=0 -nic_id=0; sleep 5'
order = 2

[[template.pass]]
role = 'child'
path = 'exp'
cmd = './simple_child -mac_id=0'
order=3

[template.placeholder]
micro_func_name = ["micro", "json", "chameleon", "compression", "helloworld", "image", "pagerank", "pyaes", "recognition"]
#loop_cmd="echo 3 | sudo tee /proc/sys/vm/drop_caches;./simple_child -mac_id=0"

